import "./globals.css"
import { ReactNode } from "react"

export const metadata = {
  title: "AI Learning Reels",
  description: "Interactive learning reels generated by AI.",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background">
        {children}
      </body>
    </html>
  )
}
